spring.config.import=optional:file:.env.docker[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST:global_postgres_db}:${DB_PORT:5432}/${DB_NAME:pikudo_db}

spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:false}
logging.level.com.pikudo=${APP_LOG_LEVEL:INFO}

management.endpoints.web.exposure.include=health,info
