spring.config.import=optional:file:.env.prod[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST:global_postgres_db}:${DB_PORT:5432}/${DB_NAME:pikudo_db}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.root=${ROOT_LOG_LEVEL:WARN}
logging.level.com.pikudo=${APP_LOG_LEVEL:INFO}

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
management.endpoints.web.exposure.include=health,info

spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX_SIZE:20}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN_IDLE:5}
spring.datasource.hikari.connection-timeout=${DB_POOL_CONNECTION_TIMEOUT:30000}
spring.datasource.hikari.idle-timeout=${DB_POOL_IDLE_TIMEOUT:600000}
spring.datasource.hikari.max-lifetime=${DB_POOL_MAX_LIFETIME:1800000}
