CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(60) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    dni VARCHAR(8) NOT NULL UNIQUE,
    telefono VARCHAR(15) NOT NULL,
    estado BOOLEAN NOT NULL,
    rol_id BIGINT NOT NULL,
    CONSTRAINT fk_usuarios_roles FOREIGN KEY (rol_id) REFERENCES roles (id)
);

CREATE TABLE IF NOT EXISTS categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL UNIQUE,
    area_preparacion VARCHAR(20),
    estado BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS mesas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero INTEGER NOT NULL UNIQUE,
    capacidad INTEGER NOT NULL,
    estado BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS configuracion_empresa (
    id BIGINT PRIMARY KEY,
    razon_social VARCHAR(255),
    ruc VARCHAR(255),
    direccion VARCHAR(255),
    telefono VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS impresoras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area VARCHAR(20) NOT NULL UNIQUE,
    ip VARCHAR(45) NOT NULL,
    puerto INTEGER NOT NULL,
    activa BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    precio NUMERIC(10, 2) NOT NULL,
    stock INTEGER NOT NULL,
    estado BOOLEAN NOT NULL,
    categoria_id BIGINT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_modificacion TIMESTAMP,
    CONSTRAINT fk_productos_categorias FOREIGN KEY (categoria_id) REFERENCES categorias (id)
);

CREATE TABLE IF NOT EXISTS pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    mesa_id BIGINT,
    mesero_id BIGINT,
    cajero_id BIGINT,
    repartidor_id BIGINT,
    total NUMERIC(10, 2) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    tipo_comprobante VARCHAR(20),
    tipo_pedido VARCHAR(20),
    direccion VARCHAR(255),
    url_maps VARCHAR(500),
    telefono_cliente VARCHAR(20),
    observaciones_pedido VARCHAR(250),
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_modificacion TIMESTAMP,
    CONSTRAINT fk_pedidos_mesas FOREIGN KEY (mesa_id) REFERENCES mesas (id),
    CONSTRAINT fk_pedidos_meseros FOREIGN KEY (mesero_id) REFERENCES usuarios (id),
    CONSTRAINT fk_pedidos_cajeros FOREIGN KEY (cajero_id) REFERENCES usuarios (id),
    CONSTRAINT fk_pedidos_repartidores FOREIGN KEY (repartidor_id) REFERENCES usuarios (id)
);

CREATE TABLE IF NOT EXISTS detalles_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10, 2) NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL,
    observaciones VARCHAR(250),
    CONSTRAINT fk_detalles_pedido_pedidos FOREIGN KEY (pedido_id) REFERENCES pedidos (id),
    CONSTRAINT fk_detalles_pedido_productos FOREIGN KEY (producto_id) REFERENCES productos (id)
);

CREATE TABLE IF NOT EXISTS comprobantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL UNIQUE,
    tipo_comprobante VARCHAR(20) NOT NULL,
    serie VARCHAR(10) NOT NULL,
    correlativo VARCHAR(20) NOT NULL,
    monto_neto NUMERIC(10, 2) NOT NULL,
    igv NUMERIC(10, 2) NOT NULL,
    monto_total NUMERIC(10, 2) NOT NULL,
    ruc VARCHAR(11),
    razon_social VARCHAR(150),
    fecha_emision TIMESTAMP NOT NULL,
    estado VARCHAR(20) NOT NULL,
    estado_sunat VARCHAR(30),
    hash_sunat VARCHAR(100),
    mensaje_sunat VARCHAR(500),
    url_pdf_sunat VARCHAR(500),
    tipo_documento_cliente VARCHAR(10),
    numero_documento_cliente VARCHAR(15),
    direccion_cliente VARCHAR(255),
    CONSTRAINT fk_comprobantes_pedidos FOREIGN KEY (pedido_id) REFERENCES pedidos (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_serie_correlativo ON comprobantes (serie, correlativo);

CREATE TABLE IF NOT EXISTS metodos_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    tipo VARCHAR(20) NOT NULL,
    activo BOOLEAN NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_modificacion TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transacciones_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comprobante_id BIGINT NOT NULL,
    metodo_pago_id BIGINT NOT NULL,
    monto NUMERIC(10, 2) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_modificacion TIMESTAMP,
    CONSTRAINT fk_transacciones_pago_comprobantes FOREIGN KEY (comprobante_id) REFERENCES comprobantes (id),
    CONSTRAINT fk_transacciones_pago_metodos FOREIGN KEY (metodo_pago_id) REFERENCES metodos_pago (id)
);

CREATE TABLE IF NOT EXISTS cajas_turnos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_caja VARCHAR(10) NOT NULL,
    usuario_id BIGINT NOT NULL,
    fecha_apertura TIMESTAMP NOT NULL,
    fecha_cierre TIMESTAMP,
    monto_inicial NUMERIC(10, 2) NOT NULL,
    monto_ventas_efectivo NUMERIC(10, 2),
    monto_ventas_tarjeta NUMERIC(10, 2),
    monto_ventas_digital NUMERIC(10, 2),
    monto_gastos NUMERIC(10, 2),
    monto_final_real NUMERIC(10, 2),
    monto_final_sistema NUMERIC(10, 2),
    observaciones VARCHAR(255),
    estado VARCHAR(20) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_modificacion TIMESTAMP,
    CONSTRAINT fk_cajas_turnos_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE TABLE IF NOT EXISTS gastos_caja (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caja_turno_id BIGINT NOT NULL,
    monto NUMERIC(10, 2) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    usuario_id BIGINT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_modificacion TIMESTAMP,
    CONSTRAINT fk_gastos_caja_cajas FOREIGN KEY (caja_turno_id) REFERENCES cajas_turnos (id),
    CONSTRAINT fk_gastos_caja_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE TABLE IF NOT EXISTS insumos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    stock_actual NUMERIC(10, 3) NOT NULL,
    stock_minimo NUMERIC(10, 3) NOT NULL,
    unidad_medida VARCHAR(20) NOT NULL,
    estado BOOLEAN NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_modificacion TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recetas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    insumo_id BIGINT NOT NULL,
    cantidad NUMERIC(10, 3) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_modificacion TIMESTAMP,
    CONSTRAINT fk_recetas_productos FOREIGN KEY (producto_id) REFERENCES productos (id),
    CONSTRAINT fk_recetas_insumos FOREIGN KEY (insumo_id) REFERENCES insumos (id)
);

CREATE TABLE IF NOT EXISTS movimientos_inventario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insumo_id BIGINT NOT NULL,
    cantidad NUMERIC(10, 3) NOT NULL,
    tipo_movimiento VARCHAR(20) NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    usuario_id BIGINT,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_modificacion TIMESTAMP,
    CONSTRAINT fk_movimientos_inventario_insumos FOREIGN KEY (insumo_id) REFERENCES insumos (id),
    CONSTRAINT fk_movimientos_inventario_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE TABLE IF NOT EXISTS zonas_reparto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    costo_envio NUMERIC(10, 2) NOT NULL,
    delimitacion VARCHAR(500),
    activo BOOLEAN NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_modificacion TIMESTAMP
);

CREATE TABLE IF NOT EXISTS direcciones_entrega (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    referencia VARCHAR(100),
    etiqueta VARCHAR(50),
    zona_reparto_id BIGINT,
    activo BOOLEAN NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_modificacion TIMESTAMP,
    CONSTRAINT fk_direcciones_entrega_clientes FOREIGN KEY (cliente_id) REFERENCES usuarios (id),
    CONSTRAINT fk_direcciones_entrega_zonas FOREIGN KEY (zona_reparto_id) REFERENCES zonas_reparto (id)
);

CREATE TABLE IF NOT EXISTS notas_credito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comprobante_id BIGINT NOT NULL UNIQUE,
    serie VARCHAR(10) NOT NULL,
    correlativo VARCHAR(20) NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    monto_devuelto NUMERIC(10, 2) NOT NULL,
    usuario_emisor_id BIGINT,
    fecha_emision TIMESTAMP NOT NULL,
    estado_sunat VARCHAR(30),
    hash_sunat VARCHAR(100),
    mensaje_sunat VARCHAR(500),
    CONSTRAINT fk_notas_credito_comprobantes FOREIGN KEY (comprobante_id) REFERENCES comprobantes (id),
    CONSTRAINT fk_notas_credito_usuarios FOREIGN KEY (usuario_emisor_id) REFERENCES usuarios (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_nc_serie_correlativo ON notas_credito (serie, correlativo);

CREATE INDEX IF NOT EXISTS idx_pedidos_estado ON pedidos (estado);
CREATE INDEX IF NOT EXISTS idx_pedidos_fecha_creacion ON pedidos (fecha_creacion);
CREATE INDEX IF NOT EXISTS idx_productos_categoria ON productos (categoria_id);
CREATE INDEX IF NOT EXISTS idx_detalles_pedido_pedido ON detalles_pedido (pedido_id);
CREATE INDEX IF NOT EXISTS idx_movimientos_inventario_insumo ON movimientos_inventario (insumo_id);
