ALTER TABLE categorias
    ADD COLUMN IF NOT EXISTS slug VARCHAR(90),
    ADD COLUMN IF NOT EXISTS descripcion VARCHAR(250),
    ADD COLUMN IF NOT EXISTS orden INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS visible_publico BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS disponible BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb;

UPDATE categorias
SET slug = lower(regexp_replace(regexp_replace(nombre, '[^a-zA-Z0-9]+', '-', 'g'), '(^-|-$)', '', 'g')) || '-' || id
WHERE slug IS NULL OR slug = '';

ALTER TABLE categorias
    ALTER COLUMN slug SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_categorias_slug ON categorias (slug);
CREATE INDEX IF NOT EXISTS idx_categorias_visible_publico ON categorias (visible_publico, disponible, orden);

ALTER TABLE productos
    ADD COLUMN IF NOT EXISTS slug VARCHAR(160),
    ADD COLUMN IF NOT EXISTS descripcion VARCHAR(500),
    ADD COLUMN IF NOT EXISTS orden INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS visible_publico BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS disponible BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS tipo_producto VARCHAR(30) NOT NULL DEFAULT 'SIMPLE',
    ADD COLUMN IF NOT EXISTS metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb;

UPDATE productos
SET slug = lower(regexp_replace(regexp_replace(nombre, '[^a-zA-Z0-9]+', '-', 'g'), '(^-|-$)', '', 'g')) || '-' || id
WHERE slug IS NULL OR slug = '';

ALTER TABLE productos
    ALTER COLUMN slug SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_productos_slug ON productos (slug);
CREATE INDEX IF NOT EXISTS idx_productos_catalogo ON productos (categoria_id, estado, visible_publico, disponible, orden);
CREATE INDEX IF NOT EXISTS idx_productos_tipo ON productos (tipo_producto);

CREATE TABLE producto_variantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    sku VARCHAR(80),
    precio_actual NUMERIC(10, 2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    disponible BOOLEAN NOT NULL DEFAULT true,
    visible_publico BOOLEAN NOT NULL DEFAULT true,
    orden INTEGER NOT NULL DEFAULT 0,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),
    fecha_modificacion TIMESTAMP,
    CONSTRAINT fk_producto_variantes_producto FOREIGN KEY (producto_id) REFERENCES productos (id),
    CONSTRAINT uq_producto_variantes_nombre UNIQUE (producto_id, nombre)
);

CREATE UNIQUE INDEX idx_producto_variantes_sku ON producto_variantes (sku) WHERE sku IS NOT NULL;
CREATE INDEX idx_producto_variantes_producto ON producto_variantes (producto_id, visible_publico, disponible, orden);

INSERT INTO producto_variantes (producto_id, nombre, precio_actual, stock, disponible, visible_publico, orden)
SELECT id, 'Base', precio, stock, estado, visible_publico, 0
FROM productos
WHERE NOT EXISTS (
    SELECT 1
    FROM producto_variantes pv
    WHERE pv.producto_id = productos.id
);

CREATE TABLE producto_precio_historial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variante_id BIGINT NOT NULL,
    precio NUMERIC(10, 2) NOT NULL,
    vigencia_desde TIMESTAMP NOT NULL DEFAULT now(),
    vigencia_hasta TIMESTAMP,
    motivo VARCHAR(120),
    creado_por_usuario_id BIGINT,
    CONSTRAINT fk_producto_precio_variante FOREIGN KEY (variante_id) REFERENCES producto_variantes (id),
    CONSTRAINT fk_producto_precio_usuario FOREIGN KEY (creado_por_usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX idx_producto_precio_variante_vigencia
    ON producto_precio_historial (variante_id, vigencia_desde DESC);

INSERT INTO producto_precio_historial (variante_id, precio, vigencia_desde, motivo)
SELECT pv.id, pv.precio_actual, now(), 'Migracion inicial catalogo real'
FROM producto_variantes pv
WHERE NOT EXISTS (
    SELECT 1
    FROM producto_precio_historial pph
    WHERE pph.variante_id = pv.id
);

CREATE TABLE producto_imagenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    variante_id BIGINT,
    storage_file_id UUID NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT false,
    orden INTEGER NOT NULL DEFAULT 0,
    alt_text VARCHAR(160),
    visible_publico BOOLEAN NOT NULL DEFAULT true,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT fk_producto_imagenes_producto FOREIGN KEY (producto_id) REFERENCES productos (id),
    CONSTRAINT fk_producto_imagenes_variante FOREIGN KEY (variante_id) REFERENCES producto_variantes (id),
    CONSTRAINT fk_producto_imagenes_storage FOREIGN KEY (storage_file_id) REFERENCES storage_files (id),
    CONSTRAINT uq_producto_imagenes_storage UNIQUE (storage_file_id)
);

CREATE INDEX idx_producto_imagenes_producto
    ON producto_imagenes (producto_id, principal DESC, orden);

CREATE TABLE producto_disponibilidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT,
    variante_id BIGINT,
    dia_semana INTEGER,
    hora_inicio TIME,
    hora_fin TIME,
    disponible BOOLEAN NOT NULL DEFAULT true,
    motivo VARCHAR(160),
    fecha_inicio DATE,
    fecha_fin DATE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT fk_producto_disponibilidades_producto FOREIGN KEY (producto_id) REFERENCES productos (id),
    CONSTRAINT fk_producto_disponibilidades_variante FOREIGN KEY (variante_id) REFERENCES producto_variantes (id),
    CONSTRAINT chk_producto_disponibilidades_owner CHECK (producto_id IS NOT NULL OR variante_id IS NOT NULL),
    CONSTRAINT chk_producto_disponibilidades_dia CHECK (dia_semana IS NULL OR dia_semana BETWEEN 1 AND 7)
);

CREATE INDEX idx_producto_disponibilidades_producto
    ON producto_disponibilidades (producto_id, dia_semana, disponible);

CREATE INDEX idx_producto_disponibilidades_variante
    ON producto_disponibilidades (variante_id, dia_semana, disponible);
