CREATE TABLE modifier_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    slug VARCHAR(150) NOT NULL UNIQUE,
    descripcion VARCHAR(300),
    min_selection INTEGER NOT NULL DEFAULT 0,
    max_selection INTEGER,
    requerido BOOLEAN NOT NULL DEFAULT false,
    activo BOOLEAN NOT NULL DEFAULT true,
    visible_publico BOOLEAN NOT NULL DEFAULT true,
    orden INTEGER NOT NULL DEFAULT 0,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),
    fecha_modificacion TIMESTAMP,
    CONSTRAINT chk_modifier_groups_selection
        CHECK (max_selection IS NULL OR min_selection <= max_selection)
);

CREATE INDEX idx_modifier_groups_visible
    ON modifier_groups (activo, visible_publico, orden);

CREATE TABLE modifiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modifier_group_id BIGINT NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    slug VARCHAR(150) NOT NULL,
    precio_extra NUMERIC(10, 2) NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT true,
    visible_publico BOOLEAN NOT NULL DEFAULT true,
    orden INTEGER NOT NULL DEFAULT 0,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),
    fecha_modificacion TIMESTAMP,
    CONSTRAINT fk_modifiers_group FOREIGN KEY (modifier_group_id) REFERENCES modifier_groups (id),
    CONSTRAINT uq_modifiers_group_slug UNIQUE (modifier_group_id, slug)
);

CREATE INDEX idx_modifiers_group_visible
    ON modifiers (modifier_group_id, activo, visible_publico, orden);

CREATE TABLE product_modifier_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    modifier_group_id BIGINT NOT NULL,
    requerido_override BOOLEAN,
    min_selection_override INTEGER,
    max_selection_override INTEGER,
    orden INTEGER NOT NULL DEFAULT 0,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT fk_product_modifier_groups_producto FOREIGN KEY (producto_id) REFERENCES productos (id),
    CONSTRAINT fk_product_modifier_groups_group FOREIGN KEY (modifier_group_id) REFERENCES modifier_groups (id),
    CONSTRAINT uq_product_modifier_groups UNIQUE (producto_id, modifier_group_id),
    CONSTRAINT chk_product_modifier_groups_selection
        CHECK (
            min_selection_override IS NULL
            OR max_selection_override IS NULL
            OR min_selection_override <= max_selection_override
        )
);

CREATE INDEX idx_product_modifier_groups_producto
    ON product_modifier_groups (producto_id, orden);

CREATE INDEX idx_product_modifier_groups_group
    ON product_modifier_groups (modifier_group_id);

CREATE TABLE combo_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    combo_producto_id BIGINT NOT NULL,
    componente_variante_id BIGINT NOT NULL,
    cantidad NUMERIC(10, 3) NOT NULL DEFAULT 1,
    requerido BOOLEAN NOT NULL DEFAULT true,
    reemplazable BOOLEAN NOT NULL DEFAULT false,
    orden INTEGER NOT NULL DEFAULT 0,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT fk_combo_components_combo_producto FOREIGN KEY (combo_producto_id) REFERENCES productos (id),
    CONSTRAINT fk_combo_components_variante FOREIGN KEY (componente_variante_id) REFERENCES producto_variantes (id),
    CONSTRAINT uq_combo_components UNIQUE (combo_producto_id, componente_variante_id),
    CONSTRAINT chk_combo_components_quantity CHECK (cantidad > 0)
);

CREATE INDEX idx_combo_components_combo
    ON combo_components (combo_producto_id, orden);

CREATE INDEX idx_combo_components_variante
    ON combo_components (componente_variante_id);
